name: compileISO and Upload

on:
  workflow_dispatch:

jobs:
  batch_clone_and_upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: git信息
      run: |
        git config --global user.email "pengguo2022@163.com"
        git config --global user.name "Polaris-P"
    - name: 环境准备
      run: |
          #sudo rm -rf /usr/share/dotnet /etc/mysql /etc/apt/sources.list.d /usr/local/lib/android /opt/ghc
          #sudo -E apt-get -y purge ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* php* android*
          sudo -E apt-get update
          sudo apt-get install subversion g++ zlib1g-dev build-essential git \
          python3 python3-distutils libncurses5-dev gawk gettext unzip \
          file libssl-dev wget libelf-dev ecj fastjar java-propose-classpath
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          df -h
    - name: 制作镜像
      run: |
        
        make download -j8
        make V=s -j1
        make -j$(nproc) V=s

    - name: 上传回仓库
      run: |
        git add .
        git commit -m "镜像制作完成"
        git push origin main
